api:
  name: "mule-self-signed"

#Temp comment to test this

azure:
  vault:
    common: "nonprodsalesforceproperties";"nonprodmaskingproperties";"nonprodcommonproperties"

hello:
  test: sdsd, gdd, dgd
