api:
  name: "mule-self-signed"

#Temp comment to test this

azure:
  vault:
    common: nonprodsalesforceproperties, nonprodcommonproperties, nonprodmaskingproperties, maskingproperties

hello:
  test: sdsd, gdd, dgd
