apiVersion: apps/v1
kind: Deployment
metadata:
  name: mule-test-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mule-test-app
  template:
    metadata:
      labels:
        app: mule-test-app
    spec:
      containers:
      - name: mule-test-app
        image: suprabhatcs/mule-test-app:473
        ports:
        - containerPort: 8081