apiVersion: v1
kind: Service
metadata:
  name: mule-test-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mule-test-app
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
   app: mule-test-app