apiVersion: v1
kind: Service
metadata:
  name: dockermule-service
spec:
  selector:
    app: dockermule
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8082
      nodePort: 30001  # specify a port between 30000 and 32767
  type: NodePort