apiVersion: v1
kind: Service
metadata:
  name: mule-gitops-service
  namespace: 60486a51-7039-4f45-b1be-a0069c86f864
spec:
  type: LoadBalancer
  selector:
    app: mule-gitops
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
   app: mule-gitops
  
